### PR TITLE
feat: output with a non-zero output code in case of a dependency resolution error

### PR DESCRIPTION
**Pull request by ermakov-oleg**
https://github.com/MousaZeidBaker/poetryup/pull/60#issuecomment-1212877999

### CODE REVIEW

**Comment by MousaZeidBaker** [comment]
Why not just use the `check=True` argument in [subprocess.run](https://docs.python.org/3/library/subprocess.html#subprocess.run) instead of wrapping it in a method and then raising our own error?

**Comment by ermakov-oleg** [comment]
If you just pass `check=True`, then in addition to the error of poerty itself, stacktrace from poetryup will get into stderr, which makes no sense in itself and only complicates the analysis of what happened, because the user needs to understand where the error really happened.

 
I used cat as a standard way of terminating on errors for the typer https://typer.tiangolo.com/tutorial/terminating/#exit-with-an-error

**Comment by MousaZeidBaker** [comment]
Wouldn't it be handy in some cases to know exactly where an error occur? Especially since we run multiple sub process. 


Also we could simply catch the error [here](https://github.com/MousaZeidBaker/poetryup/blob/master/src/poetryup/main.py#L67-L73). `pyproject.py` isn't aware (and shouldn't) of `typer`, all its logic is located in `main.py` so it's nice to keep it there. 

Example
```python
try:
    pyproject.update_dependencies(latest, without_constraint, name, group)
except subprocess.CalledProcessError as e:
    logging.debug(f"Error: {e.stderr}")
    typer.Exit(e.returncode)
```

**Comment by ermakov-oleg** [comment]
In this case `main.py` will know what's going on inside `pyproject.py`. I added `PoetryError` to prevent abstractions from leaking. 

The `stderr` is already printed for processes running through `subprocess.run`, so there's not much point in duplicating it.

**Comment by MousaZeidBaker** [comment]
Sorry for the late reply, I've been on vacation.

Made some refactoring to the code where we run commands.

**Pull request merged**
