### PR TITLE
Fix lock dependency not found, use normalized names when comparing dependencies

### PR DESCRIPTION
**Pull request by john-sandall**
Whilst PyPI normalizes package names (https://www.python.org/dev/peps/pep-0503/#normalized-names) it's possible to install packages with `_` instead of `-`, e.g. both `pip install sqlalchemy_stubs` and `pip install sqlalchemy-stubs` both work.

[This line](https://github.com/MousaZeidBaker/poetryup/blob/master/src/poetryup/pyproject.py#L45) in `pyproject.py` grabs the dependencies as specified by the user (who may be using e.g. `sqlalchemy_stubs` in `pyproject.toml`.

In this situation, [this line then errors](https://github.com/MousaZeidBaker/poetryup/blob/master/src/poetryup/pyproject.py#L102) as it doesn't find an exact match.

This small change should fix this edge case.

### CODE REVIEW

**Comment by john-sandall** [comment]
I found that this still breaks e.g. when using git installs like the following in `pyproject.toml` as then the `dependency.name` is `nb-black` and `lock_deps.name` is `nb_black`.

```
nb-black = {git = "https://github.com/dnanhkhoa/nb_black.git", rev = "be0c810503867abc4a5e9d05ba75a16fce57dfee"}
```

**Comment by MousaZeidBaker** [comment]
> Hi @john-sandall, first of all thanks for your contribution.
> 
> I wounder how you can end up with an underscore in `pyproject.toml` because when I run `poetry add sqlalchemy_stubs` command, poetry automatically replaces the underscore with a hyphen in the `pyproject.toml` file, see below. However, I think [this line](https://github.com/MousaZeidBaker/poetryup/blob/master/src/poetryup/pyproject.py#L102) should not fail if a lock dependency is not found, we should just continue to next dependency.
> 
> Peek 2022-02-03 16-25

I see now that this can happen if you manually change the `pyproject.toml` file

**Comment by john-sandall** [comment]
It's common enough for people to add packages directly to `pyproject.toml` (e.g. copy/pasting from other projects), the attitude being "it works" so why not. I see this a lot with teams I coach.

The failures you've identified are happening because you've added sqlalchemy stubs `^0.3` in `pyproject.toml` and then requesting `^0.4` (via `@latest`) in your CLI command. The [caret requirements](https://python-poetry.org/docs/dependency-specification/) means it's trying to find a version that satisfies:
- `^0.3` -> `>=0.3, <0.4`
- `^0.4` -> `>=0.4, <0.5`

hence the SolverProblemError.

If you just add in `sqlalchemy_stubs = "^0.3"` into `pyproject.toml` and run `poetry lock` and `poetry install` it should work fine regardless of `-` vs `_`

The other way you can end up with underscores in unexpected places is when installing from a git repo, which leads to a package name matching the repo name (sometimes with underscores).

**Comment by MousaZeidBaker** [comment]
> The failures you've identified are happening because you've added sqlalchemy stubs ^0.3 in pyproject.toml and then requesting ^0.4 (via @latest) in your CLI command. 

This is not true, you can use the `latest` constraint with the [poetry add command](https://python-poetry.org/docs/cli/#add) to ignore any constraint and get the latest available version. It fails only when using underscore, see following:

Peek 2022-02-06 12-48

I'm aware of people modifying `pyproject.toml` directly, what I'm arguing about is whether people should then type the correct package name. And if they don't do so, how should PoetryUp handle it? Just ignore that specific package or try to interpret the correct package name?

Regarding installing from a git repo, the package name has nothing to do with the repository name. The package name is specified in `setup.py` (or in `pyproject.toml` if poetry is used). For the nb-black package you referenced earlier, [this line](https://github.com/dnanhkhoa/nb_black/blob/master/setup.py#L15) specifies the package name, and they use underscore as the package name... This basically means packages can be named with either dashes or underscores..

**Review by MousaZeidBaker — APPROVED** [review]

**Comment by john-sandall** [comment]
Thanks for actioning this so quickly and also flagging my mistaken assumptions. I've now integrated `poetryup` into my [company's cookiecutter](https://github.com/CoefficientSystems/coefficient-cookiecutter/blob/main/%7B%7Bcookiecutter.repo_name%7D%7D/docs/updating_requirements.md) to be used with all our clients' repos going forwards, so if we notice any other issues I'll be back!

**Pull request merged**
